services:
  raw_db:
    image: postgres:alpine
    container_name: raw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ovh_finance_raw
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_raw_data:/var/lib/postgresql/data
      - ./init-scripts/raw:/docker-entrypoint-initdb.d:ro
      - ./backups/raw:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - finops_network

  warehouse:
    image: postgres:alpine
    container_name: warehouse
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ovh_finance_warehouse
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_warehouse_data:/var/lib/postgresql/data
      - ./init-scripts/warehouse:/docker-entrypoint-initdb.d:ro
      - ./backups/warehouse:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - finops_network

  grafana:
    image: grafana/grafana:13.0.2
    container_name: finops_grafana
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=dashboardNewLayouts
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - finops_network

volumes:
  postgres_raw_data:
  postgres_warehouse_data:
  grafana-storage:

networks:
  finops_network:
    driver: bridge