CREATE TABLE IF NOT EXISTS "fact_current_dynamic_compute" (
	"id" BIGINT NOT NULL,
	"instance_id" UUID,
	"fk_period_from" BIGINT,
	"fk_period_to" BIGINT,
	"fk_created_at" BIGINT,
	"fk_region" SMALLSERIAL,
	"fk_deployment_mode" SMALLSERIAL,
	"fk_resource" BIGINT,
	"fk_usage_unit" BIGINT,
	"usage_value" NUMERIC,
	"usage_price" NUMERIC,
	"fk_network_in_unit" INTEGER,
	"network_in_value" NUMERIC,
	"network_in_price" NUMERIC,
	"fk_network_out_unit" INTEGER,
	"network_out_value" NUMERIC,
	"network_out_price" NUMERIC,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_fixed_compute" (
	"id" BIGINT NOT NULL,
	"fk_activation" BIGINT,
	"fk_deployment_mode" SMALLSERIAL,
	"fk_region" SMALLSERIAL,
	"instance_id" UUID,
	"fk_resource" BIGINT,
	"price" NUMERIC,
	"fk_created_at" BIGINT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_volume" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"fk_volume" BIGINT,
	"fk_period_from" BIGINT,
	"fk_period_to" BIGINT,
	"fk_unit" INTEGER,
	"value" NUMERIC,
	"price" NUMERIC,
	"fk_created_at" BIGINT,
	"fk_resource" BIGINT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_storage" (
	"id" BIGINT NOT NULL,
	"fk_storage" BIGINT,
	"fk_period_from" BIGINT,
	"fk_period_to" BIGINT,
	"fk_in_bandwidth_unit" INTEGER,
	"in_bandwidth_value" NUMERIC,
	"in_bandwidth_price" NUMERIC,
	"fk_in_internal_bandwidth_unit" INTEGER,
	"in_internal_bandwidth_value" NUMERIC,
	"in_internal_bandwidth_price" NUMERIC,
	"fk_out_bandwidth_unit" INTEGER,
	"out_bandwidth_value" NUMERIC,
	"out_bandwidth_price" NUMERIC,
	"fk_out_internal_bandwidth_unit" INTEGER,
	"out_internal_bandwidth_value" NUMERIC,
	"out_internal_bandwidth_price" NUMERIC,
	"fk_retrieval_fees_unit" INTEGER,
	"retrieval_fees_value" NUMERIC,
	"retrieval_fees_price" NUMERIC,
	"fk_stored_unit" INTEGER,
	"stored_value" NUMERIC,
	"stored_price" NUMERIC,
	"fk_created_at" BIGINT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_rancher" (
	"id" BIGINT NOT NULL,
	"rancher_uuid" UUID,
	"fk_period_from" BIGINT,
	"fk_period_to" BIGINT,
	"fk_region" SMALLSERIAL,
	"fk_unit" INTEGER,
	"fk_deployment_mode" SMALLSERIAL,
	"value" NUMERIC,
	"price" NUMERIC,
	"created_at" BIGINT,
	"fk_resource" BIGINT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_mks" (
	"id" BIGINT NOT NULL,
	"mks_id" BIGINT,
	"fk_period_from" BIGINT,
	"fk_period_to" BIGINT,
	"fk_deployment_mode" SMALLSERIAL,
	"fk_region" SMALLSERIAL,
	"fk_resource" INTEGER,
	"fk_unit" INTEGER,
	"value" NUMERIC,
	"price" NUMERIC,
	"fk_created_at" BIGINT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_savings_plan" (
	"id" BIGINT NOT NULL,
	"name" VARCHAR(255),
	"fk_period_from" BIGINT,
	"fk_period_to" BIGINT,
	"size" INTEGER,
	"flavor" VARCHAR(255),
	"price" NUMERIC,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_instance_instance_option" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"fk_deployment_mode" SMALLSERIAL,
	"fk_region" SMALLSERIAL,
	"fk_resource" BIGINT,
	"fk_unit" INTEGER,
	"price" NUMERIC,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_volume" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"volume_uuid" UUID,
	"fk_deployment_mode" SMALLSERIAL,
	"fk_region" SMALLSERIAL,
	"fk_type" SMALLSERIAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_storage" (
	"id" BIGINT NOT NULL,
	"fk_deployment_mode" SMALLSERIAL,
	"fk_region" SMALLSERIAL,
	"fk_type" SMALLSERIAL,
	"bucket_name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_deployment_mode" (
	"id" SERIAL NOT NULL,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_time" (
	"id" BIGINT NOT NULL,
	"timestamptz" TIMESTAMPTZ,
	"year" INTEGER,
	"month" INTEGER,
	"day" INTEGER,
	"hour" INTEGER,
	"minute" INTEGER,
	"seconds" INTEGER,
	"quarter" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_region" (
	"id" SMALLSERIAL NOT NULL,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_unit" (
	"id" INTEGER NOT NULL,
	"unit" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_kubernetes" (
	"id" BIGINT NOT NULL,
	"fk_created_at" BIGINT,
	"fk_updated_at" BIGINT,
	"fk_deployed_at" BIGINT,
	"fk_deleted_at" BIGINT,
	"project_id" VARCHAR(255),
	"cluster_id" UUID,
	"nodepool_id" UUID,
	"instance_id" UUID,
	"flavor" VARCHAR(255),
	"status" VARCHAR(255),
	"version" VARCHAR(255),
	"tenant_name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_storage_type" (
	"id" SMALLSERIAL NOT NULL,
	"type" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "bridge_savings_plan_dynamic_instance" (
	"fk_instance" BIGINT NOT NULL,
	"fk_savings_plan" BIGINT NOT NULL,
	PRIMARY KEY("fk_instance", "fk_savings_plan")
);




CREATE TABLE IF NOT EXISTS "bridge_dynamic_instance_options" (
	"fk_instance" BIGINT NOT NULL,
	"fk_option" BIGINT NOT NULL,
	PRIMARY KEY("fk_instance", "fk_option")
);




CREATE TABLE IF NOT EXISTS "bridge_savings_plan_fixed_instance" (
	"fk_instance" BIGINT NOT NULL,
	"fk_savings_plan" BIGINT NOT NULL,
	PRIMARY KEY("fk_instance", "fk_savings_plan")
);




CREATE TABLE IF NOT EXISTS "bridge_fixed_instance_options" (
	"fk_instance" BIGINT NOT NULL,
	"fk_option" BIGINT NOT NULL,
	PRIMARY KEY("fk_instance", "fk_option")
);




CREATE TABLE IF NOT EXISTS "bridge_savings_plan_rancher" (
	"fk_rancher" BIGINT NOT NULL,
	"fk_savings_plan" BIGINT NOT NULL,
	PRIMARY KEY("fk_rancher", "fk_savings_plan")
);



ALTER TABLE "bridge_dynamic_instance_options"
ADD FOREIGN KEY("fk_instance") REFERENCES "fact_current_dynamic_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_dynamic_instance"
ADD FOREIGN KEY("fk_instance") REFERENCES "fact_current_dynamic_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("fk_region") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("fk_deployment_mode") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("fk_resource") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("fk_usage_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("fk_created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("fk_period_to") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("fk_period_from") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("fk_deployed_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("fk_updated_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("fk_created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_volume"
ADD FOREIGN KEY("fk_region") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_volume"
ADD FOREIGN KEY("fk_deployment_mode") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("fk_volume") REFERENCES "dim_volume"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("fk_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("fk_created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_in_bandwidth_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_in_internal_bandwidth_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_out_bandwidth_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_out_internal_bandwidth_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_retrieval_fees_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_stored_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_storage") REFERENCES "dim_storage"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_storage"
ADD FOREIGN KEY("fk_deployment_mode") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_storage"
ADD FOREIGN KEY("fk_region") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("fk_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("fk_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("fk_created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("fk_period_from") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("fk_period_to") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_period_from") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("fk_period_to") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("fk_period_from") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("fk_period_to") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("fk_period_from") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("fk_period_to") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_dynamic_instance"
ADD FOREIGN KEY("fk_savings_plan") REFERENCES "fact_current_savings_plan"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_savings_plan"
ADD FOREIGN KEY("fk_period_from") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_savings_plan"
ADD FOREIGN KEY("fk_period_to") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("fk_resource") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("fk_resource") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_rancher"
ADD FOREIGN KEY("fk_rancher") REFERENCES "fact_current_dynamic_rancher"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_rancher"
ADD FOREIGN KEY("fk_savings_plan") REFERENCES "fact_current_savings_plan"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("fk_region") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("fk_deployment_mode") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("fk_resource") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("fk_region") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("fk_deployment_mode") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("fk_activation") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("fk_resource") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("fk_deployment_mode") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("fk_region") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("fk_created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_fixed_instance"
ADD FOREIGN KEY("fk_instance") REFERENCES "fact_current_fixed_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_fixed_instance"
ADD FOREIGN KEY("fk_savings_plan") REFERENCES "fact_current_savings_plan"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_dynamic_instance_options"
ADD FOREIGN KEY("fk_option") REFERENCES "fact_current_instance_instance_option"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_instance_instance_option"
ADD FOREIGN KEY("fk_unit") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_fixed_instance_options"
ADD FOREIGN KEY("fk_instance") REFERENCES "fact_current_fixed_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_fixed_instance_options"
ADD FOREIGN KEY("fk_option") REFERENCES "fact_current_instance_instance_option"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("fk_deleted_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_volume"
ADD FOREIGN KEY("fk_type") REFERENCES "dim_storage_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_storage"
ADD FOREIGN KEY("fk_type") REFERENCES "dim_storage_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;