CREATE TABLE IF NOT EXISTS "fact_current_dynamic_compute" (
	"id" BIGSERIAL NOT NULL,
	"instance_id" UUID,
	"period_from_fk" BIGSERIAL,
	"period_to_fk" BIGSERIAL,
	"created_at_fk" BIGSERIAL,
	"region_fk" BIGSERIAL,
	"deployment_mode_fk" BIGSERIAL,
	"resource_fk" BIGSERIAL,
	"usage_unit_fk" BIGSERIAL,
	"usage_value" NUMERIC,
	"usage_price" NUMERIC,
	"network_in_unit_fk" SMALLSERIAL,
	"network_in_value" NUMERIC,
	"network_in_price" NUMERIC,
	"network_out_unit_fk" SMALLSERIAL,
	"network_out_value" NUMERIC,
	"network_out_price" NUMERIC,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_fixed_compute" (
	"id" BIGSERIAL NOT NULL,
	"activation_fk" BIGSERIAL,
	"deployment_mode_fk" SMALLSERIAL,
	"region_fk" SMALLSERIAL,
	"instance_id" UUID,
	"resource_fk" BIGSERIAL,
	"price" NUMERIC,
	"created_at_fk" BIGSERIAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_volume" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"volume_fk" INTEGER,
	"period_from_fk" INTEGER,
	"period_to_fk" INTEGER,
	"unit_id" INTEGER,
	"value" NUMERIC,
	"price" NUMERIC,
	"created_at_fk" INTEGER,
	"resource_fk" BIGSERIAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_storage" (
	"id" BIGSERIAL NOT NULL,
	"storage_fk" BIGSERIAL,
	"period_from_fk" BIGSERIAL,
	"period_to_fk" BIGSERIAL,
	"in_bandwidth_unit_fk" SMALLSERIAL,
	"in_bandwidth_value" NUMERIC,
	"in_bandwidth_price" NUMERIC,
	"in_internal_bandwidth_unit_fk" SMALLSERIAL,
	"in_internal_bandwidth_value" NUMERIC,
	"in_internal_bandwidth_price" NUMERIC,
	"out_bandwidth_unit_fk" SMALLSERIAL,
	"out_bandwidth_value" NUMERIC,
	"out_bandwidth_price" NUMERIC,
	"out_internal_bandwidth_unit_fk" SMALLSERIAL,
	"out_internal_bandwidth_value" NUMERIC,
	"out_internal_bandwidth_price" NUMERIC,
	"retrieval_fees_unit_fk" SMALLSERIAL,
	"retrieval_fees_value" NUMERIC,
	"retrieval_fees_price" NUMERIC,
	"stored_unit_fk" SMALLSERIAL,
	"stored_value" NUMERIC,
	"stored_price" NUMERIC,
	"created_at_fk" BIGSERIAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_rancher" (
	"id" BIGSERIAL NOT NULL,
	"rancher_id" UUID,
	"period_from_fk" BIGSERIAL,
	"period_to_fk" BIGSERIAL,
	"region_fk" SMALLSERIAL,
	"unit_fk" SMALLSERIAL,
	"deployment_mode_fk" SMALLSERIAL,
	"value" NUMERIC,
	"price" NUMERIC,
	"created_at" BIGSERIAL,
	"resource_fk" BIGSERIAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_dynamic_mks" (
	"id" BIGSERIAL NOT NULL,
	"mks_id" BIGSERIAL,
	"period_from_fk" BIGSERIAL,
	"period_to_fk" BIGSERIAL,
	"deployment_mode_fk" SMALLSERIAL,
	"region_fk" SMALLSERIAL,
	"resource_fk" SMALLSERIAL,
	"unit_id" SMALLSERIAL,
	"value" NUMERIC,
	"price" NUMERIC,
	"created_at_fk" BIGSERIAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_savings_plan" (
	"id" BIGSERIAL NOT NULL,
	"name" VARCHAR(255),
	"period_from_fk" BIGSERIAL,
	"period_to_fk" BIGSERIAL,
	"size" INTEGER,
	"flavor" VARCHAR(255),
	"price" NUMERIC,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "fact_current_instance_instance_option" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"deployment_mode_fk" SMALLSERIAL,
	"region_fk" SMALLSERIAL,
	"resource_fk" BIGSERIAL,
	"unit_fk" SMALLSERIAL,
	"price" NUMERIC,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_volume" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"volume_id" UUID,
	"deployment_mode_id" INTEGER,
	"region_id" INTEGER,
	"type" SMALLSERIAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_storage" (
	"id" BIGSERIAL NOT NULL,
	"deployment_mode_id" SMALLSERIAL,
	"region_id" SMALLSERIAL,
	"type_fk" SMALLSERIAL,
	"bucket_name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_deployment_mode" (
	"id" SMALLSERIAL NOT NULL,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_time" (
	"id" BIGSERIAL NOT NULL,
	"timestamptz" TIMESTAMPTZ,
	"year" SMALLINT,
	"month" SMALLINT,
	"day" SMALLINT,
	"hour" SMALLINT,
	"minute" SMALLINT,
	"seconds" SMALLINT,
	"quarter" SMALLINT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_region" (
	"id" SMALLSERIAL NOT NULL,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_unit" (
	"id" SMALLSERIAL NOT NULL,
	"unit" VARCHAR(255),
	"measure_type" VARCHAR(255),
	"standard_unit" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_kubernetes" (
	"id" BIGSERIAL NOT NULL,
	"created_at" BIGSERIAL,
	"updated_at" BIGSERIAL,
	"deployed_at" BIGSERIAL,
	"deletion_at_fk" BIGSERIAL,
	"project_id" VARCHAR(255),
	"cluster_id" UUID,
	"nodepool_id" UUID,
	"instance_id" UUID,
	"flavor" VARCHAR(255),
	"status" VARCHAR(255),
	"version" VARCHAR(255),
	"tenant_name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "dim_storage_type" (
	"id" SMALLSERIAL NOT NULL,
	"type" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "bridge_savings_plan_dynamic_instance" (
	"instance_fk" BIGSERIAL NOT NULL,
	"savings_plan_fk" BIGSERIAL NOT NULL,
	PRIMARY KEY("instance_fk", "savings_plan_fk")
);




CREATE TABLE IF NOT EXISTS "bridge_dynamic_instance_options" (
	"instance_fk" BIGSERIAL NOT NULL,
	"option_fk" BIGSERIAL NOT NULL,
	PRIMARY KEY("instance_fk", "option_fk")
);




CREATE TABLE IF NOT EXISTS "bridge_savings_plan_fixed_instance" (
	"instance_fk" BIGSERIAL NOT NULL,
	"savings_plan_fk" BIGSERIAL NOT NULL,
	PRIMARY KEY("instance_fk", "savings_plan_fk")
);




CREATE TABLE IF NOT EXISTS "bridge_fixed_instance_options" (
	"instance_fk" BIGSERIAL NOT NULL,
	"option_fk" BIGSERIAL NOT NULL,
	PRIMARY KEY("instance_fk", "option_fk")
);




CREATE TABLE IF NOT EXISTS "bridge_savings_plan_rancher" (
	"rancher_fk" BIGSERIAL NOT NULL,
	"savings_plan_fk" BIGSERIAL NOT NULL,
	PRIMARY KEY("rancher_fk", "savings_plan_fk")
);



ALTER TABLE "bridge_dynamic_instance_options"
ADD FOREIGN KEY("instance_fk") REFERENCES "fact_current_dynamic_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_dynamic_instance"
ADD FOREIGN KEY("instance_fk") REFERENCES "fact_current_dynamic_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("region_fk") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("deployment_mode_fk") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("resource_fk") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("usage_unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("created_at_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("period_to_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_compute"
ADD FOREIGN KEY("period_from_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("deployed_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("updated_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_volume"
ADD FOREIGN KEY("region_id") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_volume"
ADD FOREIGN KEY("deployment_mode_id") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("volume_fk") REFERENCES "dim_volume"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("unit_id") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("created_at_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("in_bandwidth_unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("in_internal_bandwidth_unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("out_bandwidth_unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("out_internal_bandwidth_unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("retrieval_fees_unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("stored_unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("created_at_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("storage_fk") REFERENCES "dim_storage"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_storage"
ADD FOREIGN KEY("deployment_mode_id") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_storage"
ADD FOREIGN KEY("region_id") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("created_at") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("unit_id") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("created_at_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("period_from_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("period_to_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("period_from_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_storage"
ADD FOREIGN KEY("period_to_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("period_from_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("period_to_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("period_from_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("period_to_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_dynamic_instance"
ADD FOREIGN KEY("savings_plan_fk") REFERENCES "fact_current_savings_plan"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_savings_plan"
ADD FOREIGN KEY("period_from_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_savings_plan"
ADD FOREIGN KEY("period_to_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_volume"
ADD FOREIGN KEY("resource_fk") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("resource_fk") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_rancher"
ADD FOREIGN KEY("rancher_fk") REFERENCES "fact_current_dynamic_rancher"("rancher_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_rancher"
ADD FOREIGN KEY("savings_plan_fk") REFERENCES "fact_current_savings_plan"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("region_fk") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_rancher"
ADD FOREIGN KEY("deployment_mode_fk") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("resource_fk") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("region_fk") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_dynamic_mks"
ADD FOREIGN KEY("deployment_mode_fk") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("activation_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("resource_fk") REFERENCES "dim_kubernetes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("deployment_mode_fk") REFERENCES "dim_deployment_mode"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("region_fk") REFERENCES "dim_region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_fixed_compute"
ADD FOREIGN KEY("created_at_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_fixed_instance"
ADD FOREIGN KEY("instance_fk") REFERENCES "fact_current_fixed_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_savings_plan_fixed_instance"
ADD FOREIGN KEY("savings_plan_fk") REFERENCES "fact_current_savings_plan"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_dynamic_instance_options"
ADD FOREIGN KEY("option_fk") REFERENCES "fact_current_instance_instance_option"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_current_instance_instance_option"
ADD FOREIGN KEY("unit_fk") REFERENCES "dim_unit"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_fixed_instance_options"
ADD FOREIGN KEY("instance_fk") REFERENCES "fact_current_fixed_compute"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bridge_fixed_instance_options"
ADD FOREIGN KEY("option_fk") REFERENCES "fact_current_instance_instance_option"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_kubernetes"
ADD FOREIGN KEY("deletion_at_fk") REFERENCES "dim_time"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_volume"
ADD FOREIGN KEY("type") REFERENCES "dim_storage_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_storage"
ADD FOREIGN KEY("type_fk") REFERENCES "dim_storage_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;